---
all:
  children:
    homelab:
      hosts:
        # Example server definitions:
        # node1.homelab:
        #   ansible_host: 192.168.1.10
        # node2.homelab:
        #   ansible_host: 192.168.1.11
    local:
      hosts:
        localhost:
          ansible_connection: local
